### PR TITLE
added and updated events section

### PR DESCRIPTION
**Pull request by nikki1016**
Issue Number #37 
added events section, compress images and remove useless css folder to maintain repository structure
[Live Link](https://nikki1016.github.io/testing/)

### CODE REVIEW

**Comment by gauthamzz** [comment]
The seperate page for events is nice, i was thinking we just keep that. 
But if you want to keep both, keep the section of events under goals section.

Its your choice.

**Comment by nikki1016** [comment]
what should be there then in goals section for events....only link to next page or some evnts list + link to next page?

**Comment by gauthamzz** [comment]
just put the events under the goals section,its fine.change the order

**Comment by nikki1016** [comment]
please have a look and let me now if any changes needed [live link](https://nikki1016.github.io/testing)

**Comment by gauthamzz** [comment]
looks good, fix the merge conflicts. 

Btw the events you added, they are all event outside india. I was thinking of only keeo events which are applicabe to us. But thats another issue for another day.

**Comment by gauthamzz** [comment]
The code to inspire part looks weird. lets make events under womens organisations . then it will be fine.

**Pull request closed without merging**
