### PR TITLE
Update Goals section

### PR DESCRIPTION
**Pull request by ritikamotwani**
Issue Number #53 
Changes proposed in this pull request :
Updated the goals section
Link: https://ritikamotwani.github.io/Girls-who-code

### CODE REVIEW

**Comment by gauthamzz** [comment]
It doesnt look fancy 😄 
But i like text written. I guess its the font size or lack of a graphic image. Could you try something.

**Comment by ritikamotwani** [comment]
Link: https://ritikamotwani.github.io/Girls-who-code/
@gauthamzz please review.

**Comment by gauthamzz** [comment]
deepinscreenshot_select-area_20180119030535
Is this what you added?

idk why you added github logo.

what i was saying earlier was the things you wrote doesnt look clear. Just increase font weight or something ,

**Comment by ritikamotwani** [comment]
This is how it should have appeared. It was looking good. I'll see what else can be done.
image

**Comment by ritikamotwani** [comment]
Link: https://ritikamotwani.github.io/Girls-who-code/#goals
@gauthamzz have a look.

**Pull request merged**
