### PR TITLE
issue #31

### PR DESCRIPTION
**Pull request by muskanchugh5**
Issue Number #31 
Changes proposed in this pull request :code,develop..in one line
[Live Link](provide link here)https://muskan6769.github.io/Girls-who-code/

### CODE REVIEW

**Comment by gauthamzz** [comment]
can you change the background image as well. It has no clairty.

**Comment by muskanchugh5** [comment]
that blue image(the first one)??

**Comment by gauthamzz** [comment]
Yeah the first one

**Comment by gauthamzz** [comment]
@muskan6769 fix merge conflicts

**Review by gauthamzz — APPROVED** [review]

**Comment by muskanchugh5** [comment]
i just resolved the merge conflicts ...even there is an option to resolve conflicts....so is it done or not??

**Comment by gauthamzz** [comment]
It’s not resolved 😅

**Comment by gauthamzz** [comment]
And change the background image related to women who code

**Comment by muskanchugh5** [comment]
okkk

**Pull request merged**
