### PR TITLE
Added new starter bootstrap template

### PR DESCRIPTION
**Pull request by Panda2498**
Do I need to add or delete any other folders or docs?

### CODE REVIEW

**Comment by PaiShoIroh** [comment]
Yes. There are files missing which you need you add.
Whenever you're using CSS or script files, you need to push them together with the index.html file.
 
I'll recommend you turn on gh-pages and make sure that the website works as you want it to and then generate a pull requests. Sometimes files go missing and everything breaks down.

#### Right now the pages looks like this.
Simply add the other .css and .js files and it'll work
image

**Comment by Panda2498** [comment]
What should be  the content of other.css and . js file and do i need to add
it in the folder?

**Comment by aswinzz** [comment]
If you see the current directoru structure you will get to know where js and css files should be added and give the links of the css and js files correctly

**Comment by Anupam-dagar** [comment]
@Panda2498 most of the times starter template come in a zip file, you can push all the contents of that zip.
For example.
http://materializecss.com/getting-started.html
you can visit the above link and scroll down to see the starter template, you can download that zip and you get the whole code, you need to push that code.
P.S Don't push materialise starter template until and unless you can't find any other starter template :stuck_out_tongue:

**Review by Anupam-dagar — APPROVED** [review]

**Comment by Panda2498** [comment]
I pushed the template yesterday itself! :)

**Pull request merged**
