### PR TITLE
add a fork me on github

### PR DESCRIPTION
**Pull request by Sangeetaaa**
Issue Number #75
Changes proposed in this pull request :adding a fork me on github ribbon
[Live Link](https://sangeeta2499.github.io/Girls-who-code/)

### CODE REVIEW

**Comment by gauthamzz** [comment]
You need to fix merge conclicts after sending pr :/

**Comment by gauthamzz** [comment]
fix merge conflicts asap or im closing this

**Comment by ritikamotwani** [comment]
There has been no activity to fix the conflicts. I would like to work on this.

**Comment by Anupam-dagar** [comment]
@ritikamotwani yeah sure :smile:

**Pull request closed without merging**
