### PR TITLE
fix footer mobile view

### PR DESCRIPTION
**Pull request by Tlazypanda**
Issue Number #
Changes proposed in this pull request :
[Live Link](provide link here)

### CODE REVIEW

**Comment by Tlazypanda** [comment]
Is this alright? @Anupam-dagar ?

**Comment by Tlazypanda** [comment]
https://tlazypanda.github.io/Girls-who-code/

**Comment by Anupam-dagar** [comment]
last minute PR's 😛

**Comment by Tlazypanda** [comment]
yeah sir exactly at 11.59!!!! 😄

**Pull request merged**
